[2016-04-26 04:52:41] request.INFO: Matched route "AdonaiUsuarios_docente". {"route_parameters":{"_controller":"Adonai\\UnicoBundle\\Controller\\DefaultController::docenteAction","_route":"AdonaiUsuarios_docente"},"request_uri":"http://adonai-sga.sytes.net/ProyectoFinal/web/docente_panel"} []
[2016-04-26 04:52:41] security.DEBUG: Read existing security token from the session. {"key":"_security_admin_area"} []
[2016-04-26 04:52:41] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-04-26 04:52:41] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\ProyectoFinal\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2016-04-26 04:52:41] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at C:\xampp\htdocs\ProyectoFinal\vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ExceptionListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\xampp\\htdocs\\ProyectoFinal\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\ExceptionListener.php:119, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\ProyectoFinal\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2016-04-26 04:52:41] security.DEBUG: Stored the security token in the session. {"key":"_security_admin_area"} []
[2016-04-26 04:56:33] request.INFO: Matched route "AdonaiUsuarios_docente". {"route_parameters":{"_controller":"Adonai\\UnicoBundle\\Controller\\DefaultController::docenteAction","_route":"AdonaiUsuarios_docente"},"request_uri":"http://adonai-sga.sytes.net/ProyectoFinal/web/docente_panel"} []
[2016-04-26 04:56:33] security.DEBUG: Read existing security token from the session. {"key":"_security_admin_area"} []
[2016-04-26 04:56:33] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-04-26 04:56:33] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\ProyectoFinal\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2016-04-26 04:56:33] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at C:\xampp\htdocs\ProyectoFinal\vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ExceptionListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\xampp\\htdocs\\ProyectoFinal\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\ExceptionListener.php:119, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\ProyectoFinal\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2016-04-26 04:56:33] security.DEBUG: Stored the security token in the session. {"key":"_security_admin_area"} []
[2016-04-26 05:32:52] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /app-dev.php"" at C:\xampp\htdocs\ProyectoFinal\app\cache\prod\classes.php line 2599 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /app-dev.php\" at C:\\xampp\\htdocs\\ProyectoFinal\\app\\cache\\prod\\classes.php:2599, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\ProyectoFinal\\app\\cache\\prod\\appProdUrlMatcher.php:1005)"} []
[2016-04-26 06:55:55] request.INFO: Matched route "AdonaiUsuarios_docente_notas". {"route_parameters":{"_controller":"Adonai\\UnicoBundle\\Controller\\DefaultController::notasDocenteAction","_route":"AdonaiUsuarios_docente_notas"},"request_uri":"http://adonai-sga.sytes.net/ProyectoFinal/web/docente_notas"} []
[2016-04-26 06:55:55] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-04-26 06:55:55] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function getIdDoc() on null" at C:\xampp\htdocs\ProyectoFinal\src\Adonai\UnicoBundle\Controller\DefaultController.php line 85 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function getIdDoc() on null at C:\\xampp\\htdocs\\ProyectoFinal\\src\\Adonai\\UnicoBundle\\Controller\\DefaultController.php:85)"} []
[2016-04-26 07:00:36] request.INFO: Matched route "AdonaiUsuarios_docente_notas". {"route_parameters":{"_controller":"Adonai\\UnicoBundle\\Controller\\DefaultController::notasDocenteAction","_route":"AdonaiUsuarios_docente_notas"},"request_uri":"http://adonai-sga.sytes.net/ProyectoFinal/web/docente_notas"} []
[2016-04-26 07:00:36] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-04-26 07:00:36] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function getIdDoc() on null" at C:\xampp\htdocs\ProyectoFinal\src\Adonai\UnicoBundle\Controller\DefaultController.php line 85 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function getIdDoc() on null at C:\\xampp\\htdocs\\ProyectoFinal\\src\\Adonai\\UnicoBundle\\Controller\\DefaultController.php:85)"} []
[2016-04-27 02:36:06] request.INFO: Matched route "AdonaiUsuarios_docente_notas". {"route_parameters":{"_controller":"Adonai\\UnicoBundle\\Controller\\DefaultController::notasDocenteAction","_route":"AdonaiUsuarios_docente_notas"},"request_uri":"http://localhost/ProyectoFinal/web/docente_notas"} []
[2016-04-27 02:36:06] security.DEBUG: Read existing security token from the session. {"key":"_security_admin_area"} []
[2016-04-27 02:36:06] security.DEBUG: User was reloaded from a user provider. {"username":"docente1","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-04-27 02:36:06] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Controller "Adonai\UnicoBundle\Controller\DefaultController::notasDocenteAction" for URI "/docente_notas" is not callable." at C:\xampp\htdocs\ProyectoFinal\app\cache\prod\classes.php line 2660 {"exception":"[object] (InvalidArgumentException(code: 0): Controller \"Adonai\\UnicoBundle\\Controller\\DefaultController::notasDocenteAction\" for URI \"/docente_notas\" is not callable. at C:\\xampp\\htdocs\\ProyectoFinal\\app\\cache\\prod\\classes.php:2660)"} []
[2016-04-27 02:36:07] security.DEBUG: Stored the security token in the session. {"key":"_security_admin_area"} []
[2016-04-27 02:38:56] request.INFO: Matched route "AdonaiUsuarios_docente_notas". {"route_parameters":{"_controller":"Adonai\\UnicoBundle\\Controller\\DefaultController::notasDocenteAction","_route":"AdonaiUsuarios_docente_notas"},"request_uri":"http://localhost/ProyectoFinal/web/docente_notas"} []
[2016-04-27 02:38:56] security.DEBUG: Read existing security token from the session. {"key":"_security_admin_area"} []
[2016-04-27 02:38:56] security.DEBUG: User was reloaded from a user provider. {"username":"docente1","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-04-27 02:38:56] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Controller "Adonai\UnicoBundle\Controller\DefaultController::notasDocenteAction" for URI "/docente_notas" is not callable." at C:\xampp\htdocs\ProyectoFinal\app\cache\prod\classes.php line 2660 {"exception":"[object] (InvalidArgumentException(code: 0): Controller \"Adonai\\UnicoBundle\\Controller\\DefaultController::notasDocenteAction\" for URI \"/docente_notas\" is not callable. at C:\\xampp\\htdocs\\ProyectoFinal\\app\\cache\\prod\\classes.php:2660)"} []
[2016-04-27 02:38:57] security.DEBUG: Stored the security token in the session. {"key":"_security_admin_area"} []
[2016-04-27 02:42:59] request.INFO: Matched route "AdonaiUsuarios_docente_notas". {"route_parameters":{"_controller":"Adonai\\UnicoBundle\\Controller\\DefaultController::notasDocenteAction","_route":"AdonaiUsuarios_docente_notas"},"request_uri":"http://localhost/ProyectoFinal/web/docente_notas"} []
[2016-04-27 02:42:59] security.DEBUG: Read existing security token from the session. {"key":"_security_admin_area"} []
[2016-04-27 02:42:59] security.DEBUG: User was reloaded from a user provider. {"username":"docente1","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-04-27 02:42:59] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Controller "Adonai\UnicoBundle\Controller\DefaultController::notasDocenteAction" for URI "/docente_notas" is not callable." at C:\xampp\htdocs\ProyectoFinal\app\cache\prod\classes.php line 2660 {"exception":"[object] (InvalidArgumentException(code: 0): Controller \"Adonai\\UnicoBundle\\Controller\\DefaultController::notasDocenteAction\" for URI \"/docente_notas\" is not callable. at C:\\xampp\\htdocs\\ProyectoFinal\\app\\cache\\prod\\classes.php:2660)"} []
[2016-04-27 02:43:00] security.DEBUG: Stored the security token in the session. {"key":"_security_admin_area"} []
[2016-04-27 05:45:41] request.INFO: Matched route "notas_index". {"route_parameters":{"_controller":"Adonai\\UnicoBundle\\Controller\\NotasController::indexAction","_route":"notas_index"},"request_uri":"http://localhost/ProyectoFinal/web/notas/"} []
[2016-04-27 05:45:41] security.DEBUG: Read existing security token from the session. {"key":"_security_admin_area"} []
[2016-04-27 05:45:41] security.DEBUG: User was reloaded from a user provider. {"username":"docente1","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-04-27 05:45:42] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "planeadores_index" as such route does not exist.") in "AdonaiUnicoBundle:Notas:notas_docente.html.twig" at line 18." at C:\xampp\htdocs\ProyectoFinal\app\cache\prod\classes.php line 5334 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"planeadores_index\" as such route does not exist.\") in \"AdonaiUnicoBundle:Notas:notas_docente.html.twig\" at line 18. at C:\\xampp\\htdocs\\ProyectoFinal\\app\\cache\\prod\\classes.php:5334, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"planeadores_index\" as such route does not exist. at C:\\xampp\\htdocs\\ProyectoFinal\\app\\cache\\prod\\appProdUrlGenerator.php:121)"} []
[2016-04-27 05:45:42] security.DEBUG: Stored the security token in the session. {"key":"_security_admin_area"} []
[2016-04-27 17:32:20] request.INFO: Matched route "AdonaiUsuarios_docente_notas". {"route_parameters":{"_controller":"Adonai\\UnicoBundle\\Controller\\DefaultController::notasDocenteAction","_route":"AdonaiUsuarios_docente_notas"},"request_uri":"http://localhost/ProyectoFinal/web/docente_notas"} []
[2016-04-27 17:32:20] security.DEBUG: Read existing security token from the session. {"key":"_security_admin_area"} []
[2016-04-27 17:32:20] security.DEBUG: User was reloaded from a user provider. {"username":"docente1","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-04-27 17:32:20] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Controller "Adonai\UnicoBundle\Controller\DefaultController::notasDocenteAction" for URI "/docente_notas" is not callable." at C:\xampp\htdocs\ProyectoFinal\app\cache\prod\classes.php line 2660 {"exception":"[object] (InvalidArgumentException(code: 0): Controller \"Adonai\\UnicoBundle\\Controller\\DefaultController::notasDocenteAction\" for URI \"/docente_notas\" is not callable. at C:\\xampp\\htdocs\\ProyectoFinal\\app\\cache\\prod\\classes.php:2660)"} []
[2016-04-27 17:32:20] security.DEBUG: Stored the security token in the session. {"key":"_security_admin_area"} []
[2016-04-28 04:17:11] request.INFO: Matched route "AdonaiUsuarios_docente_notas". {"route_parameters":{"_controller":"Adonai\\UnicoBundle\\Controller\\DefaultController::notasDocenteAction","_route":"AdonaiUsuarios_docente_notas"},"request_uri":"http://localhost/ProyectoFinal/web/docente_notas"} []
[2016-04-28 04:17:11] security.DEBUG: Read existing security token from the session. {"key":"_security_admin_area"} []
[2016-04-28 04:17:11] security.DEBUG: User was reloaded from a user provider. {"username":"docente1","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-04-28 04:17:11] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Controller "Adonai\UnicoBundle\Controller\DefaultController::notasDocenteAction" for URI "/docente_notas" is not callable." at C:\xampp\htdocs\ProyectoFinal\app\cache\prod\classes.php line 2660 {"exception":"[object] (InvalidArgumentException(code: 0): Controller \"Adonai\\UnicoBundle\\Controller\\DefaultController::notasDocenteAction\" for URI \"/docente_notas\" is not callable. at C:\\xampp\\htdocs\\ProyectoFinal\\app\\cache\\prod\\classes.php:2660)"} []
[2016-04-28 04:17:11] security.DEBUG: Stored the security token in the session. {"key":"_security_admin_area"} []
